title: Stephan Tomforde
description: Stephan Tomforde ist ein Techniker, Denker und jemand, der gerne Dinge mit Sinn baut.
social_media_share_image: /images/01.jpg
disqus-identifier:
google-analytics: G-05SK2CNMCN